#!/usr/bin/env bash
# macOS 开发环境安装脚本（必须用 bash 运行，不要把内容粘进 zsh）
#
# 安装内容：
#   - Git、Python 3.12、Node.js 22、pnpm
#   - MySQL 8.4、Redis（Homebrew 当前为 8.x，兼容 7.x 用法）
#   - Eclipse Temurin JDK 8 / 17 / 21
#
# 用法（任选一种）：
#   bash scripts/setup-mac-dev.sh
#   chmod +x scripts/setup-mac-dev.sh && ./scripts/setup-mac-dev.sh
#
# 装完后新开一个终端，可用：
#   jdk8 / jdk17 / jdk21    切换 Java 版本（默认 17，适合 Android）

set -euo pipefail

if [[ "$(uname -s)" != "Darwin" ]]; then
  echo "这个脚本只用于 macOS。" >&2
  exit 1
fi

if [[ -z "${BASH_VERSION:-}" ]]; then
  echo "请用 bash 运行：bash $0" >&2
  exit 1
fi

if ! xcode-select -p >/dev/null 2>&1; then
  cat >&2 <<'EOF'
还没有安装 Command Line Developer Tools，Homebrew 无法继续。

请先完成其中一种：
  1) 终端执行：xcode-select --install
  2) 若提示无法从软件更新服务器获得，到下面页面登录 Apple ID，
     下载对应系统的 Command Line Tools .dmg 并安装：
     https://developer.apple.com/download/all/?q=Command%20Line%20Tools

装好后再运行本脚本。
EOF
  exit 1
fi

append_source_line() {
  local rc_file="$1"
  local marker_begin="# >>> mac-dev-setup begin"
  local marker_end="# <<< mac-dev-setup end"
  local block
  block=$(cat <<'EOF'
# >>> mac-dev-setup begin
[ -f "$HOME/.mac-dev-setup.sh" ] && . "$HOME/.mac-dev-setup.sh"
# <<< mac-dev-setup end
EOF
)
  mkdir -p "$(dirname "$rc_file")"
  touch "$rc_file"
  if grep -Fqs "$marker_begin" "$rc_file"; then
    local tmp
    tmp="$(mktemp)"
    awk -v begin="$marker_begin" -v end="$marker_end" '
      $0 == begin { skip=1; next }
      $0 == end { skip=0; next }
      skip != 1 { print }
    ' "$rc_file" >"$tmp"
    printf '\n%s\n' "$block" >>"$tmp"
    mv "$tmp" "$rc_file"
  else
    printf '\n%s\n' "$block" >>"$rc_file"
  fi
}

echo "==> 安装 Homebrew（已安装则跳过）"
if ! command -v brew >/dev/null 2>&1; then
  NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if [[ -x /opt/homebrew/bin/brew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
elif [[ -x /usr/local/bin/brew ]]; then
  eval "$(/usr/local/bin/brew shellenv)"
else
  echo "找不到 brew，请检查 Homebrew 是否安装成功。" >&2
  exit 1
fi

echo "==> 更新 Homebrew 并安装语言 / 数据库"
brew update
brew install \
  git \
  "python@3.12" \
  "node@22" \
  pnpm \
  "mysql@8.4" \
  redis

echo "==> 安装 JDK 8 / 17 / 21（Eclipse Temurin）"
brew install --cask "temurin@8" "temurin@17" "temurin@21"

echo "==> 启动 MySQL 与 Redis"
brew services start "mysql@8.4"
brew services start redis

echo "==> 写入 ~/.mac-dev-setup.sh 和环境加载语句"
cat >"$HOME/.mac-dev-setup.sh" <<'EOF'
# Generated by scripts/setup-mac-dev.sh — do not paste this into zsh by hand.

if [ -x /opt/homebrew/bin/brew ]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
elif [ -x /usr/local/bin/brew ]; then
  eval "$(/usr/local/bin/brew shellenv)"
fi

if command -v brew >/dev/null 2>&1; then
  _py="$(brew --prefix 'python@3.12' 2>/dev/null)/libexec/bin"
  _node="$(brew --prefix 'node@22' 2>/dev/null)/bin"
  _mysql="$(brew --prefix 'mysql@8.4' 2>/dev/null)/bin"
  [ -d "$_py" ] && PATH="$_py:$PATH"
  [ -d "$_node" ] && PATH="$_node:$PATH"
  [ -d "$_mysql" ] && PATH="$_mysql:$PATH"
  unset _py _node _mysql
fi

if [ -x /usr/libexec/java_home ]; then
  JAVA_8_HOME="$(/usr/libexec/java_home -v 1.8 2>/dev/null || true)"
  JAVA_17_HOME="$(/usr/libexec/java_home -v 17 2>/dev/null || true)"
  JAVA_21_HOME="$(/usr/libexec/java_home -v 21 2>/dev/null || true)"
  export JAVA_8_HOME JAVA_17_HOME JAVA_21_HOME
fi

# Android / Gradle 默认使用 JDK 17
if [ -z "${JAVA_HOME:-}" ] || [ ! -d "${JAVA_HOME:-}" ]; then
  if [ -n "${JAVA_17_HOME:-}" ]; then
    JAVA_HOME="$JAVA_17_HOME"
  elif [ -n "${JAVA_21_HOME:-}" ]; then
    JAVA_HOME="$JAVA_21_HOME"
  elif [ -n "${JAVA_8_HOME:-}" ]; then
    JAVA_HOME="$JAVA_8_HOME"
  fi
fi
[ -n "${JAVA_HOME:-}" ] && PATH="$JAVA_HOME/bin:$PATH"
export JAVA_HOME PATH

jdk8() {
  if [ -z "${JAVA_8_HOME:-}" ]; then
    echo "未找到 JDK 8" >&2
    return 1
  fi
  export JAVA_HOME="$JAVA_8_HOME"
  export PATH="$JAVA_HOME/bin:$PATH"
  java -version
}

jdk17() {
  if [ -z "${JAVA_17_HOME:-}" ]; then
    echo "未找到 JDK 17" >&2
    return 1
  fi
  export JAVA_HOME="$JAVA_17_HOME"
  export PATH="$JAVA_HOME/bin:$PATH"
  java -version
}

jdk21() {
  if [ -z "${JAVA_21_HOME:-}" ]; then
    echo "未找到 JDK 21" >&2
    return 1
  fi
  export JAVA_HOME="$JAVA_21_HOME"
  export PATH="$JAVA_HOME/bin:$PATH"
  java -version
}
EOF

append_source_line "$HOME/.zprofile"
append_source_line "$HOME/.zshrc"
append_source_line "$HOME/.bash_profile"

# 当前 shell 立刻生效（若用户是 bash 运行脚本）
# shellcheck disable=SC1090
. "$HOME/.mac-dev-setup.sh"

sleep 3

echo
echo "======== 安装结果 ========"
printf 'git:        '; git --version || true
printf 'python3.12: '; python3.12 --version || true
printf 'python3:    '; python3 --version || true
printf 'node:       '; node -v || true
printf 'pnpm:       '; pnpm -v || true
printf 'mysql:      '; mysql --version || true
printf 'redis:      '; redis-server --version || true
printf 'redis ping: '; redis-cli ping || true
echo "MySQL:"
mysql -u root -e "SELECT VERSION();" 2>/dev/null || echo "  （若刚启动失败，等几秒后执行：mysql -u root -e 'SELECT VERSION();'）"
echo
echo "已安装的 JDK："
/usr/libexec/java_home -V 2>&1 || true
echo
printf '当前 java:  JAVA_HOME=%s\n' "${JAVA_HOME:-未设置}"
java -version 2>&1 || true
echo "=========================="
echo
echo "请新开一个终端窗口，然后可以执行："
echo "  python3 --version && node -v && pnpm -v && git --version"
echo "  mysql -u root -e 'SELECT VERSION();' && redis-cli ping"
echo "  jdk8    # 切换到 Java 8"
echo "  jdk17   # 切换到 Java 17（默认，适合当前 Android Gradle）"
echo "  jdk21   # 切换到 Java 21"
echo
echo "Homebrew 默认 MySQL root 无密码，仅本机可连。"
